language: elixir
os: linux
dist: trusty

before_script:
  - |
  wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo dpkg -i erlang-solutions_2.0_all.deb
  apt-get update
  apt-get install esl-erlang
  apt-get install elixir


script:
  - MIX_ENV=test mix do test
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
